---
# tasks file for wordpress
- name: Download do Wordpress
  become: true
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no


- name: Extract Wordpress
  become: true
  unarchive:
    src=/tmp/wordpress.tar.gz
    dest=/var/www/
    copy=no


- name: Atualiza config do Apache 2
  become: true
  lineinfile:
    dest=/etc/apache2/sites-enabled/000-default.conf
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify:
  - restart apache


- name: Copiar arquivo wp-config.php
  become: true
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php


- name: Atualizar config do wordpress
  become: true
  lineinfile:
    dest=/var/www/wordpress/wp-config.php
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - {regexp: 'database_name_here', line: "define('DB_NAME', '{{wp_mysql_db}}');"}
    - {regexp: 'username_here', line: "define('DB_USER', '{{wp_mysql_user}}');"}
    - {regexp: 'password_here', line: "define('DB_PASSWORD', '{{wp_mysql_password}}');"}
