---
# tasks file for server

- name: Atualiza o cache do APT
  apt: update_cache=yes cache_valid_time=3600
  become: yes


- name: Instalar os pacotes do servidor
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - apache2
    - mysql-server
    - php7.4-mysql
    - php7.4
    - libapache2-mod-php7.4
    - python3-mysqldb
